[package]
name = "queue-attempt-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cty = "0.2.2"
memmap2 = "0.9.4"
static_assertions = "1.1.0"

[build-dependencies]
cc = "1.0"
